package owasp.mstg.uncrackable1;

/* This class is generated by JADX */
public final class R {

    public static final class dimen {
        public static final int activity_horizontal_margin = 2130771968;
        public static final int activity_vertical_margin = 2130771969;
    }

    public static final class id {
        public static final int action_settings = 2130837504;
        public static final int edit_text = 2130837505;
    }

    public static final class layout {
        public static final int activity_main = 2130903040;
    }

    public static final class menu {
        public static final int menu_main = 2130968576;
    }

    public static final class mipmap {
        public static final int ic_launcher = 2131034112;
    }

    public static final class string {
        public static final int action_settings = 2131099648;
        public static final int app_name = 2131099649;
        public static final int button_verify = 2131099650;
        public static final int edit_text = 2131099651;
        public static final int thanks = 2131099652;
    }

    public static final class style {
        public static final int AppTheme = 2131165184;
    }
}
